spring:
  application:
    name: Orient Portal
  profiles:
    active: dev
  thymeleaf:
    cache: true # Enable template caching.
    check-template: true # Check that the template exists before rendering it.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html
  aop:
    proxy-target-class: true

---

spring:
  profiles: dev
  datasource:
      username: OrientTDM_grid_test2
      password: goodluck
      url: jdbc:oracle:thin:@//192.168.89.193:1521/orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver

cas:
  prefixUrl: http://192.168.89.240:8999/cas
  loginUrl: ${cas.prefixUrl}/login
  serviceUrl: http://192.168.88.24:${server.port}
  callbackUrl: ${cas.serviceUrl}/callback
jwt:
  salt: 12345678901234567890123456789012
debug: true
server:
  port: 8080

logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG

mybatis:
    type-aliases-package: com.orient.portal.domain.model
    type-handlers-package: com.orient.portal.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
---

spring:
  profiles: production
  datasource:
    username: OrientTDM_grid_test2
    password: goodluck
    url: jdbc:oracle:thin:@//192.168.89.193:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver


cas:
  prefixUrl: http://192.168.89.240:8999/cas
  loginUrl: ${cas.prefixUrl}/login
  serviceUrl: http://192.168.88.24:${server.port}
  callbackUrl: ${cas.serviceUrl}/callback
jwt:
  salt: 12345678901234567890123456789012
debug: true
server:
  port: 8080

logging:
  file: logs/production_app.log
  level:
    root: WARN

---

